### ISSUE TITLE
Peer-to-peer-morning-session-reviews

### ISSUE THREAD

**Issue by naanmohammed** [mutugi-c/Portfolio#6]
-The code is well-organized and easily readable. However the identation of li is a bit off on line 27-29.

**Comment by fredo509** [comment]
- Your design look beautiful your can just hidden the nav menu on resize screen for mobile version 

After good work

**Comment by Ruthmy** [comment]
Hi Chris! I really like your project and how you have advanced it.
I saw that you use BEM and I think that's really nice. My only recommendation to you would be to review the names of the classes, some of them do not fully comply with the methodology. This will keep the classification you already have homogeneous and make it easily readable.
Hope this help you. Thanks for sharing your work with us.

**Comment by mutugi-c** [comment]
Thank you very much, guys, for your comments and recommendations. I'm already incorporating them into my portfolio.
